pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Clean workspace and checkout the code from the GitHub repository
                cleanWs()
                git branch: 'main', url: 'https://github.com/sidgolangade/Web-Application-Repository.git'
            }
        }
        stage('Deploy to Ansible Server') {
            steps {
                // Copy the built application code to the Ansible Server
                withCredentials([sshUserPrivateKey(credentialsId: '2a67236b-f587-44a4-90f2-1e8ba1e8d313', keyFileVariable: 'SSH_PRIVATE_KEY')]) {
                    sh '''
                    rsync -e "ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY" -av --exclude venv/ ./ ec2-user@ec2-44-203-115-252.compute-1.amazonaws.com:/home/ec2-user/ansible-data/
                    '''
                }
            }
        }
        stage('Deploy using Ansible') {
            steps {
                // Run Ansible playbook on the Ansible Server
                withCredentials([sshUserPrivateKey(credentialsId: '2a67236b-f587-44a4-90f2-1e8ba1e8d313', keyFileVariable: 'SSH_PRIVATE_KEY')]) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$SSH_PRIVATE_KEY" ec2-user@ec2-44-203-115-252.compute-1.amazonaws.com 'ansible-playbook -i /etc/ansible/hosts /home/ec2-user/ansible-data/ansible-playbooks/deploy-web-app.yml'
                    '''
                }
            }
        }
    }
    post {
        success {
            echo 'Web App Deployment successful!'
            // Actions to be executed when the pipeline is successful.
        }
        failure {
            echo 'Web App Deployment failed!'
            // Actions to be executed when the pipeline fails.
        }
    }
}